name: Convert Markdown to HTML

on:
  push:
    paths:
      - '**/*.md' # Only trigger the workflow for Markdown file changes

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Convert to HTML
        uses: joshmgross/markdown-processor@v2.2.2
        with:
          files: 'README.md'
          output-dir: 'docs'
